name: Build APK

on: [push, workflow_dispatch]

jobs:

  flutterBuild:
    name: Flutter Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}

      - name: build
        run: |
          flutter clean
          flutter pub get
          flutter build apk

      - name: Upload Artefato
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release
